site_name: AUT-DT document

repo_url: https://github.com/AUT/Digital_Twin

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.sections
    - navigation.footer
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md

  - Getting started:
    - Quick Start Demo: GettingStarted/QuickStartDemo/index.md
    #- (TODO) Setup Unity Project: GettingStarted/SetupUnityProject/index.md

  # - Introduction:
  #   - Autoware: Introduction/Autoware/index.md
  #   - AWSIM: Introduction/AWSIM/index.md
  #   - CombinationWithAutoware: Introduction/CombinationWithAutoware/index.md

  # - Project guide:
  #   - Directory: ProjectGuide/Directory/index.md
  #   - Scenes: ProjectGuide/Scenes/index.md
  #   - Git Branch: ProjectGuide/GitBranch/index.md
  #   - External Libraries: ProjectGuide/ExternalLibraries/index.md

  - Developer guide:
    - How to Contribute: DeveloperGuide/HowToContribute/index.md
    - Trouble shooting: DeveloperGuide/TroubleShooting/index.md
    - Documentation: DeveloperGuide/Documentation/index.md
    - License : DeveloperGuide/License/index.md
    - Contact : DeveloperGuide/Contact/index.md
